### PR TITLE
Newhcc

### PR DESCRIPTION
**Pull request by andrzejnovak**
- Add TF plotting routines

@nsmith- does this need to be made more general (mostly pT/msd bins I guess)

### CODE REVIEW

**Review by nsmith- — APPROVED** [review]
I'm not sure what all the plotters do but some look generally useful for rhalphabet stuff. Perhaps others might edit them to generalize?

**Comment by nsmith-** [comment]
Can you update the branch and fix the flake8 errors?

**Comment by andrzejnovak** [comment]
Yeah, I didn't mean this to go in as is, I always forget to open PRs as drafts
- `rhalphalib/plot/input_shapes.py ` takes rl pickle file and create a mock root directory like structure compatible with fitDiagnostics output for input x-checks
- `plotTF` is a smooth TF plot
- `plotTF_ratio` is a bin/discrete TF plot
- `plot_qcd` I'll take out
- `plot_cov` is just nicer plot from fitDiag

**Comment by andrzejnovak** [comment]
@nsmith- cleaned up the linter, sorry for the delay

**Review by nsmith- — APPROVED** [review]

**Pull request merged**
