### PR TITLE
Fix smoothstep formula

### LINKED ISSUE #15: Smoothstep implementation is wrong
From Thiago, the formula at https://github.com/nsmith-/rhalphalib/blob/cdab8c8f42379cc31bfee1dd6878e5d061e1d907/rhalphalib/parameter.py#L280 doesn't behave as it should, blowing up at large values.
I think `(((0.1875*x*x - 0.625)*x*x + 0.9375)*x + 0.5)*(x > -1)*(x < 1) + 1*(x >= 1)` is what it should be.

### PR DESCRIPTION
**Pull request by nsmith-**
Fixes #15

### CODE REVIEW

**Comment by nsmith-** [comment]
Checking the conditions with jax:
```python
import jax
import jax.numpy as jnp

formula = lambda x: (((0.1875*x*x - 0.625)*x*x + 0.9375)*x + 0.5)*(x > -1)*(x < 1) + 1*(x >= 1)
x = jnp.linspace(-3, 3, 100)
plt.plot(x, formula(x), x, jax.vmap(jax.grad(formula), 0)(x), x, jax.vmap(jax.grad(jax.grad(formula)), 0)(x))
plt.legend(["f(x)", "f'(x)", "f''(x)"])
plt.show()
```
gives
Figure_1

**Comment by trtomei** [comment]
Hi @nsmith- 

For the record: why don't we use a "regular" logistic function, like f(x) = 0.5 + 0.5*tanh(0.5*x)?

**Comment by nsmith-** [comment]
To zeroth order, we want to be consistent with combine.
After that, a desirable property is that the template at x=1 matches exactly the 1-sigma variation. (the template interpolation uses smoothStep as follows: https://github.com/nsmith-/rhalphalib/blob/master/rhalphalib/sample.py#L291-L294)
I'm not sure if this is the best solution, would be interested to hear the history of it. It only really matters when you have asymmetric nuisance parameter effects anyway.

**Review by jmduarte — COMMENTED** [review]
@nsmith-  looks good to me, but actually I'm a little confused. If I take the old formula and plot it, I get the exact same thing. Is the issue in the `TMath::Sign()` calls?

```python
import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt

formula = lambda x: (((0.1875*x*x - 0.625)*x*x + 0.9375)*x + 0.5)*(1+x > 0)*(1-x > 0) + 1 - (1-x > 0)
x = jnp.linspace(-3, 3, 100)
plt.plot(x, formula(x), x, jax.vmap(jax.grad(formula), 0)(x), x, jax.vmap(jax.grad(jax.grad(formula)), 0)(x))
plt.legend(["f(x)", "f'(x)", "f''(x)"])
plt.show()
```

old

**Comment by nsmith-** [comment]
Well now I'm more confused, either it was working ok previously or now its equally broken. @trtomei or @mcremone did you test this out already?

**Comment by nsmith-** [comment]
I guess it must be `TMath::Sign` then? Merging

**Pull request merged**
