### PR TITLE
feat: add warning if shape systs are off

### PR DESCRIPTION
**Pull request by andrzejnovak**
@nsmith- should I do this with logging instead?

### CODE REVIEW

**Review by nsmith- — CHANGES_REQUESTED** [review]
I guess the logging infrastructure was never put together for this, but it seems like a good long-term plan. In the mean time you could use `warnings.warn`

**Comment by andrzejnovak** [comment]
Yeah, but would probably take some `with warnings.filterwarnings('always')` since this should report in each case. Is that really preferable to a print?

**Comment by nsmith-** [comment]
Ah I forgot about repeat warnings behavior, in that case yeah print for now I guess :/

**Review by nsmith- — APPROVED** [review]

**Comment by andrzejnovak** [comment]
@nsmith- should I merge this myself then?

**Comment by nsmith-** [comment]
Sure!

**Pull request merged**
