### PR TITLE
Return hist after morphing if provided a hist

### PR DESCRIPTION
**Pull request by jmduarte**
- Return hist after morphing if provided a hist
- otherwise return a tuple

### CODE REVIEW

**Comment by rkansal47** [comment]
LGTM! I switched it to using `hist.axis.Variable` in case the bins are not regularly spaced, let me know if that messed it up.

**Review by rkansal47 — APPROVED** [review]

**Comment by nsmith-** [comment]
The PR test failed because it was not able to edit the branch you made. Can you allow edits from maintainers / run the formatter?

**Comment by rkansal47** [comment]
@nsmith- I think maintainers are already allowed to edit:

Screenshot 2024-06-06 at 09 47 47

@jmduarte maybe you need to change the workflow permissions? (Or I think running black would work too.)

Screenshot 2024-06-06 at 09 48 07

**Comment by jmduarte** [comment]
ok, fixed permissions / ran black now

**Comment by nsmith-** [comment]
Thanks!

**Pull request merged**
